/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dennnoval.ui;

import com.dennnoval.datamodel.BarangModel;
import com.dennnoval.entity.Barang;
import com.dennnoval.ui.tablemodel.AdminTableModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author dennnoval
 */
public class FormBarang extends javax.swing.JFrame {

  /**
   * Creates new form FormBarang
   */
  public FormBarang() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    kodeBrgTxt = new javax.swing.JTextField();
    namaBrgTxt = new javax.swing.JTextField();
    hargaBrgTxt = new javax.swing.JTextField();
    simpanBtn = new javax.swing.JButton();
    editBtn = new javax.swing.JButton();
    hapusBtn = new javax.swing.JButton();
    clearBtn = new javax.swing.JButton();
    cariTxt = new javax.swing.JTextField();
    jButton5 = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    stokBrgTxt = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setResizable(false);

    jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Form Barang");

    jLabel2.setFont(new java.awt.Font(".SF NS Text", 0, 14)); // NOI18N
    jLabel2.setText("Kode Barang");

    jLabel3.setFont(new java.awt.Font(".SF NS Text", 0, 14)); // NOI18N
    jLabel3.setText("Nama Barang");

    jLabel4.setFont(new java.awt.Font(".SF NS Text", 0, 14)); // NOI18N
    jLabel4.setText("Harga Barang");

    simpanBtn.setText("SIMPAN");
    simpanBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        simpanBtnActionPerformed(evt);
      }
    });

    editBtn.setText("EDIT");
    editBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        editBtnActionPerformed(evt);
      }
    });

    hapusBtn.setText("HAPUS");
    hapusBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        hapusBtnActionPerformed(evt);
      }
    });

    clearBtn.setText("CLEAR");
    clearBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        clearBtnActionPerformed(evt);
      }
    });

    cariTxt.addInputMethodListener(new java.awt.event.InputMethodListener() {
      public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
        cariTxtInputMethodTextChanged(evt);
      }
      public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
      }
    });
    cariTxt.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cariTxtActionPerformed(evt);
      }
    });

    jButton5.setText("Cari");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton5ActionPerformed(evt);
      }
    });

    jTable1.setFont(new java.awt.Font(".SF NS Text", 0, 14)); // NOI18N
    jTable1.setModel(new AdminTableModel.TableBarang());
    jTable1.setEditingColumn(0);
    jTable1.setEditingRow(0);
    jTable1.setRowHeight(30);
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTable1MouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(jTable1);

    jLabel5.setFont(new java.awt.Font(".SF NS Text", 0, 14)); // NOI18N
    jLabel5.setText("Cari");

    jLabel6.setFont(new java.awt.Font(".SF NS Text", 0, 14)); // NOI18N
    jLabel6.setText("Stok");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addGap(16, 16, 16)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel3)
                  .addComponent(jLabel4)
                  .addComponent(jLabel2)
                  .addComponent(jLabel6))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(kodeBrgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(namaBrgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(hargaBrgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(stokBrgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addComponent(jLabel5)
                  .addGap(18, 18, 18)
                  .addComponent(cariTxt)
                  .addGap(18, 18, 18)
                  .addComponent(jButton5))
                .addGroup(layout.createSequentialGroup()
                  .addComponent(simpanBtn)
                  .addGap(18, 18, 18)
                  .addComponent(editBtn)
                  .addGap(31, 31, 31)
                  .addComponent(hapusBtn)
                  .addGap(18, 18, 18)
                  .addComponent(clearBtn))))
            .addGap(0, 13, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(16, 16, 16)
        .addComponent(jLabel1)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(kodeBrgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(namaBrgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(hargaBrgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(stokBrgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel6))
        .addGap(36, 36, 36)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(simpanBtn)
          .addComponent(editBtn)
          .addComponent(hapusBtn)
          .addComponent(clearBtn))
        .addGap(30, 30, 30)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cariTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButton5)
          .addComponent(jLabel5))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(21, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void cariTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariTxtActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_cariTxtActionPerformed

  private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
    String kode = kodeBrgTxt.getText();
    String nama = namaBrgTxt.getText();
    int harga = Integer.valueOf(hargaBrgTxt.getText());
    int stok = Integer.valueOf(stokBrgTxt.getText());
    Barang brg = new Barang(kode, nama, harga, stok);
    boolean isInserted = new BarangModel().create(brg);
    if (isInserted) {
      ((DefaultTableModel)jTable1.getModel()).addRow(new Object[]{
        brg.getKode(), brg.getNama(), brg.getHarga(), brg.getStok()
      });
      JOptionPane.showMessageDialog(rootPane, "Tambah data berhasil!");
    } else {
      JOptionPane.showMessageDialog(rootPane, "Tambah data gagal!");
    }
  }//GEN-LAST:event_simpanBtnActionPerformed

  private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    int row = jTable1.getSelectedRow();
    String kode = jTable1.getValueAt(row, 0).toString();
    String nama = jTable1.getValueAt(row, 1).toString();
    String harga = jTable1.getValueAt(row, 2).toString();
    String stok = jTable1.getValueAt(row, 3).toString();
    kodeBrgTxt.setText(kode);
    namaBrgTxt.setText(nama);
    hargaBrgTxt.setText(harga);
    stokBrgTxt.setText(stok);
  }//GEN-LAST:event_jTable1MouseClicked

  private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
    String kode = kodeBrgTxt.getText();
    String nama = namaBrgTxt.getText();
    int harga = Integer.valueOf(hargaBrgTxt.getText());
    int stok = Integer.valueOf(stokBrgTxt.getText());
    Barang brg = new Barang(kode, nama, harga, stok);
    boolean isDeleted = new BarangModel().delete(brg);
    if (isDeleted) {
      int row = jTable1.getSelectedRow();
      ((DefaultTableModel)jTable1.getModel()).removeRow(row);
      JOptionPane.showMessageDialog(rootPane, "Hapus data berhasil!");
    } else {
      JOptionPane.showMessageDialog(rootPane, "Hapus data gagal!");
    }
  }//GEN-LAST:event_hapusBtnActionPerformed

  private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
    String kode = kodeBrgTxt.getText();
    String nama = namaBrgTxt.getText();
    int harga = Integer.valueOf(hargaBrgTxt.getText());
    int stok = Integer.valueOf(stokBrgTxt.getText());
    Barang brg = new Barang(kode, nama, harga, stok);
    boolean isUpdated = new BarangModel().update(brg);
    if (isUpdated) {
      int row = jTable1.getSelectedRow();
      jTable1.setValueAt(brg.getKode(), row, 0);
      jTable1.setValueAt(brg.getNama(), row, 1);
      jTable1.setValueAt(brg.getHarga(), row, 2);
      jTable1.setValueAt(brg.getStok(), row, 3);
      JOptionPane.showMessageDialog(rootPane, "Edit data berhasil!");
    } else {
      JOptionPane.showMessageDialog(rootPane, "Edit data gagal!");
    }
  }//GEN-LAST:event_editBtnActionPerformed

  private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
    kodeBrgTxt.setText("");
    namaBrgTxt.setText("");
    hargaBrgTxt.setText("");
    stokBrgTxt.setText("");
  }//GEN-LAST:event_clearBtnActionPerformed

  private void cariTxtInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cariTxtInputMethodTextChanged
    // TODO add your handling code here:
  }//GEN-LAST:event_cariTxtInputMethodTextChanged

  private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    String filterText = cariTxt.getText();
    TableRowSorter<AdminTableModel.TableBarang> sorter = new TableRowSorter<>((AdminTableModel.TableBarang)jTable1.getModel());
    RowFilter<AdminTableModel.TableBarang, Object> rf;
    rf = RowFilter.regexFilter(filterText, 1);
    sorter.setRowFilter(rf);
    jTable1.setRowSorter(sorter);
  }//GEN-LAST:event_jButton5ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
  }

  @Override
  public void dispose() {
    super.dispose();
    Admin admFrm = new Admin();
    admFrm.setLocationRelativeTo(null);
    admFrm.setVisible(true);
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField cariTxt;
  private javax.swing.JButton clearBtn;
  private javax.swing.JButton editBtn;
  private javax.swing.JButton hapusBtn;
  private javax.swing.JTextField hargaBrgTxt;
  private javax.swing.JButton jButton5;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  private javax.swing.JTextField kodeBrgTxt;
  private javax.swing.JTextField namaBrgTxt;
  private javax.swing.JButton simpanBtn;
  private javax.swing.JTextField stokBrgTxt;
  // End of variables declaration//GEN-END:variables
}
